server:
  port: ${PORT:8081}

app:
  kafka:
    topics:
      todo-created:  ms-todo-created

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    username: user
    password: password
    url: jdbc:h2:file:./database/h2.db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1

  h2:
    console:
      path: /h2-console
      settings:
        trace: true
      enabled: true
  jpa:
    show-sql: true




management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    root: warn
    com.melardev: trace
    org.springframework.web: debug
    org.apache.kafka: trace

