server:
  # the port used most of the times is 8888, I used 8889 just to prove that config clients are configured as expected
  # because by default they all fetch from localhost:8888 so if you indeed use the default server port, even if you have made
  # a misconfiguration your config clients will still work because they fetch anyways from localhost:8888, so let's run our config server
  # at 8889, that way, any mis-configured config client will show up with a error.
  port: ${PORT:8889}

spring:
  application:
    name: config-service

  cloud:
    config:
      label: master
      server:
        git:
          clone-on-start: false
          uri: https://github.com/melardev/Java_SpringCloud_Eureka_Zuul_Config_Kafka_ProxyDiscovery_RestCrud
          search-paths:
            - "config-services-properties"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: error
    org.springframework: info
    com.melardev: debug


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
